project_id = "fsbhbfltathfcpvcjfzt"

[functions.fetch-exercises]
verify_jwt = false

[functions.proxy-exercise-image]
verify_jwt = false


[functions.get-vapid-public-key]
verify_jwt = false

[functions.send-chat-push]
verify_jwt = false

[functions.generate-ai-program]
verify_jwt = false

[functions.test-push]
verify_jwt = false

[functions.create-sub-coach]
verify_jwt = false

[functions.send-coaching-invite]
verify_jwt = false

[functions.inbound-email]
verify_jwt = false

[functions.send-custom-email]
verify_jwt = false

[functions.handle-automation]
verify_jwt = false

[functions.trigger-welcome-email]
verify_jwt = false
