
INSERT INTO public.supplements_library (name, category, default_dosage, description, icon)
SELECT v.name, v.category, v.default_dosage, v.description, v.icon
FROM (VALUES
  -- mg
  ('Magnezyum Bisglisinat','Mineral','400 mg','Yüksek biyoyararlanıma sahip magnezyum formu','💊'),
  ('Çinko Pikolinat','Mineral','30 mg','Bağışıklık ve testosteron desteği','💊'),
  ('Ashwagandha KSM-66','Adaptojen','600 mg','Stres ve kortizol regülasyonu','🌿'),
  ('Alpha-GPC','Nootropik','300 mg','Kolinerjik nörotransmitter desteği','🧠'),
  ('Koenzim Q10','Antioksidan','200 mg','Mitokondriyal enerji üretimi','💊'),
  ('Demir Kelat','Mineral','18 mg','Anemi önleme ve oksijen taşıma','💊'),
  ('Rhodiola Rosea','Adaptojen','300 mg','Mental dayanıklılık ve adaptasyon','🌿'),
  ('C Vitamini (Askorbik Asit)','Vitamin','1000 mg','Antioksidan ve kolajen sentezi','💊'),
  ('Kafein Anhidroz','Stimülan','200 mg','Akut performans ve odak','💊'),
  ('L-Theanine','Nootropik','200 mg','Sakin odak ve kafein dengesi','🧠'),
  ('Resveratrol','Antioksidan','250 mg','Hücresel uzun ömür desteği','🌿'),
  ('Devedikeni (Silymarin)','Karaciğer','250 mg','Karaciğer detoks desteği','🌿'),
  ('Saw Palmetto','Hormon','320 mg','Prostat sağlığı','🌿'),
  ('NAC (N-Asetil Sistein)','Antioksidan','600 mg','Glutatyon öncüsü','💊'),
  ('Potasyum Sitrat','Mineral','500 mg','Elektrolit ve kas fonksiyonu','💊'),
  ('B6 Vitamini','Vitamin','50 mg','Nörotransmitter sentezi','💊'),
  ('B12 Metilkobalamin','Vitamin','1 mg','Enerji ve sinir sistemi','💊'),
  ('Kurkumin','Antienflamatuar','500 mg','Eklem ve sistemik inflamasyon','🌿'),
  ('Quercetin','Antioksidan','500 mg','Mast hücre stabilizatörü','🌿'),
  ('L-Tirozin','Amino','500 mg','Stres altında dopamin sentezi','💊'),
  ('Bromelain','Enzim','500 mg','Protein sindirim enzimi','💊'),
  ('Pterostilbene','Antioksidan','100 mg','Resveratrol analoğu','🌿'),
  ('Berberin','Metabolik','500 mg','Glukoz metabolizması','🌿'),
  ('Lion''s Mane','Nootropik','500 mg','BDNF ve sinir büyüme faktörü','🍵'),
  ('Reishi','Adaptojen','500 mg','Bağışıklık modülatörü','🍵'),
  ('Cordyceps','Adaptojen','500 mg','Aerobik kapasite','🍵'),
  ('Spirulina','Süperfood','500 mg','Bitkisel protein ve klorofil','🍵'),
  ('Chlorella','Süperfood','500 mg','Detoks ve klorofil','🍵'),
  ('Bacopa Monnieri','Nootropik','300 mg','Hafıza ve öğrenme','🌿'),
  ('Boswellia','Antienflamatuar','300 mg','Eklem sağlığı','🌿'),
  ('Glisin','Amino','3000 mg','Uyku kalitesi ve kolajen','💊'),
  ('DIM','Hormon','200 mg','Östrojen metabolizması','💊'),
  ('Tongkat Ali','Hormon','200 mg','Doğal testosteron desteği','🌿'),
  ('Fenugreek','Hormon','500 mg','Libido ve T desteği','🌿'),
  ('Maca','Adaptojen','1500 mg','Endürans ve libido','🌿'),
  ('Tribulus Terrestris','Hormon','750 mg','Saponin bazlı T desteği','🌿'),
  ('Pygeum','Hormon','100 mg','Prostat sağlığı','🌿'),
  ('Lutein','Göz','20 mg','Maküla pigment desteği','💊'),
  ('Astaxanthin','Antioksidan','12 mg','Güçlü karotenoid','💊'),
  ('Pycnogenol','Antioksidan','100 mg','Vasküler sağlık','🌿'),
  ('L-Lysine','Amino','1000 mg','Esansiyel amino asit','💊'),
  ('L-Ornithine','Amino','1000 mg','Amonyak klirensi','💊'),
  ('Phosphatidylserine','Nootropik','100 mg','Kortizol regülasyonu','🧠'),
  ('Inositol','Nootropik','500 mg','Anksiyete ve insülin','💊'),
  ('TMG (Betaine Anhydrous)','Performans','2500 mg','Homosistein ve güç','💊'),
  ('Choline Bitartrate','Nootropik','500 mg','Asetilkolin öncüsü','🧠'),
  ('Sodyum Hyaluronate','Eklem','120 mg','Eklem ve cilt nemi','💊'),
  ('MSM','Eklem','1000 mg','Kükürt bazlı eklem desteği','💊'),
  ('Curcumin C3 Complex','Antienflamatuar','500 mg','Standartize kurkuminoid','🌿'),
  ('Garcinia Cambogia','Metabolik','500 mg','HCA bazlı iştah desteği','🌿'),
  -- g
  ('Creapure Kreatin Monohidrat','Performans','5 g','Altın standart kreatin','🧪'),
  ('L-Glutamin','Amino','5 g','Bağırsak ve iyileşme','🧪'),
  ('AAKG (Arginine Alpha-Ketoglutarat)','Pump','3 g','NO öncüsü','🧪'),
  ('L-Citrulline Malate','Pump','6 g','NO ve laktat tamponu','🧪'),
  ('Beta-Alanin','Performans','3 g','Karnozin sentezi','🧪'),
  ('BCAA 2:1:1','Amino','7 g','Dallı zincirli amino','🧪'),
  ('EAA (Esansiyel Aminoasitler)','Amino','10 g','Tam profil amino','🧪'),
  ('Whey Protein Isolate','Protein','30 g','Hızlı emilim izole protein','🧪'),
  ('Mikselar Kazein','Protein','30 g','Yavaş salınımlı protein','🧪'),
  ('D-Aspartik Asit','Hormon','3 g','LH ve T desteği','🧪'),
  ('Taurin','Amino','2 g','Hücresel hidrasyon','🧪'),
  ('Carnosyn Beta-Alanin','Performans','3 g','Patentli beta-alanin','🧪'),
  ('HMB','Performans','3 g','Antikatabolik metabolit','🧪'),
  ('Hidrolize Kollajen Peptit','Eklem','10 g','Eklem ve cilt kollajeni','🧪'),
  ('Whey Concentrate','Protein','30 g','Geleneksel whey formu','🧪'),
  ('Vegan Pea Protein','Protein','30 g','Bezelye bazlı protein','🧪'),
  ('Inulin Lif','Sindirim','5 g','Prebiyotik lif','🧪'),
  ('Psyllium Husk','Sindirim','5 g','Çözünür lif','🧪'),
  ('Glikomannan','Tokluk','3 g','Konjac kökü lifi','🧪'),
  ('Maltodextrin','Karbonhidrat','40 g','Hızlı emilim karb','🧪'),
  ('Cluster Dextrin','Karbonhidrat','40 g','HBCD intra-workout','🧪'),
  ('Waxy Maize','Karbonhidrat','40 g','Mum mısır nişastası','🧪'),
  ('Spirulina Powder','Süperfood','5 g','Toz spirulina','🍵'),
  ('Greens Powder','Süperfood','8 g','Yeşil karışım','🍵'),
  ('Karboksilatlı Sitrülin','Pump','8 g','Yüksek doz sitrülin','🧪'),
  ('Agmatine Sulfate','Pump','1 g','Uzun süreli NO desteği','🧪'),
  ('Pre-Workout Blend','Performans','15 g','Kombine ön-antrenman','🧪'),
  ('Intra-Workout Carb','Karbonhidrat','30 g','Antrenman içi yakıt','🧪'),
  ('L-Carnitine L-Tartrate','Yağ Yakıcı','3 g','Toparlanma ve yağ','🧪'),
  -- IU
  ('D3 Vitamini (Kolekalsiferol)','Vitamin','5000 IU','Kemik ve bağışıklık','☀️'),
  ('A Vitamini (Retinil Palmitat)','Vitamin','10000 IU','Görme ve cilt','💉'),
  ('E Vitamini (dl-Alfa Tokoferil)','Vitamin','400 IU','Yağda çözünen antioksidan','💉'),
  -- Kapsül
  ('Multivitamin Formülü','Multivitamin','2 Kapsül','Tam spektrum vitamin-mineral','💊'),
  ('ZMA','Mineral','3 Kapsül','Çinko-magnezyum-B6','💊'),
  ('Sarımsak Ekstresi','Kardiyovasküler','1 Kapsül','Allicin bazlı','🌿'),
  ('Ginkgo Biloba','Nootropik','1 Kapsül','Serebral kan akımı','🌿'),
  ('Pre-Probiotik 25M CFU','Sindirim','1 Kapsül','Yüksek CFU probiyotik','💊'),
  ('Adrenal Support','Adaptojen','2 Kapsül','Adrenal toparlanma','💊'),
  ('Joint Support Stack','Eklem','2 Kapsül','Çoklu eklem matriksi','💊'),
  ('Liver Detox Complex','Karaciğer','2 Kapsül','Hepatik destek karışımı','💊'),
  ('Test Booster Complex','Hormon','3 Kapsül','Doğal T destek karışımı','💊'),
  ('Sleep Support Blend','Uyku','2 Kapsül','Melatonin + bitkisel','💊'),
  ('Fat Burner Thermo','Yağ Yakıcı','2 Kapsül','Termojenik karışım','💊'),
  ('Estrogen Blocker','Hormon','1 Kapsül','Aromataz inhibitörü','💊'),
  ('DHEA','Hormon','1 Kapsül','Pregnenolon türevi','💊'),
  ('5-HTP','Nootropik','1 Kapsül','Serotonin öncüsü','💊'),
  ('GABA','Nootropik','2 Kapsül','İnhibitör nörotransmitter','💊'),
  -- Softgel
  ('Omega-3 Balık Yağı (Yüksek EPA/DHA)','Yağ Asidi','2 Softgel','Yüksek EPA/DHA yağ asitleri','🐟'),
  ('CLA','Yağ Yakıcı','3 Softgel','Konjuge linoleik asit','🐟'),
  ('Krill Yağı','Yağ Asidi','2 Softgel','Fosfolipid bağlı omega','🐟'),
  ('MCT Softgel','Yağ Asidi','3 Softgel','Orta zincirli trigliserit','🐟'),
  ('Vitamin K2 MK-7','Vitamin','1 Softgel','Kemik ve damar sağlığı','🐟'),
  ('Tongkat Ali Softgel','Hormon','1 Softgel','Yağ bazlı tongkat','🐟'),
  ('Borage Oil GLA','Yağ Asidi','1 Softgel','Gamma linolenik asit','🐟'),
  ('Evening Primrose Oil','Yağ Asidi','1 Softgel','Hormonal denge','🐟'),
  ('Lecithin','Nootropik','1 Softgel','Fosfolipid kompleksi','🐟'),
  ('Astaksantin Softgel','Antioksidan','1 Softgel','Yağ bazlı astaksantin','🐟'),
  -- Tablet
  ('Glukozamin + Kondroitin + MSM','Eklem','3 Tablet','Triple eklem matriksi','💊'),
  ('Aspirin Düşük Doz','Kardiyovasküler','1 Tablet','Kan sulandırıcı','💊'),
  ('Iron Bisglycinate Tablet','Mineral','1 Tablet','Hassas mide demir formu','💊'),
  ('Iodine Kelp','Mineral','1 Tablet','Tiroid desteği','💊'),
  ('Niacin (B3)','Vitamin','1 Tablet','Lipid metabolizması','💊'),
  ('Selenyum','Mineral','1 Tablet','Tiroid antioksidanı','💊'),
  ('Krom Pikolinat','Mineral','1 Tablet','Glukoz duyarlılığı','💊'),
  -- ml
  ('Likit L-Karnitin','Yağ Yakıcı','15 ml','Hızlı emilen sıvı karnitin','🧪'),
  ('D3+K2 Damla','Vitamin','1 ml','Yağ bazlı vitamin damlası','☀️'),
  ('MCT Oil','Yağ Asidi','15 ml','Saf MCT yağı','🐟'),
  ('Likit Amino Hidrator','Amino','30 ml','İçilebilir amino karışımı','🧪'),
  ('Apple Cider Vinegar Liquid','Metabolik','15 ml','Elma sirkesi tonik','🌿'),
  ('Likit Magnezyum','Mineral','10 ml','Hızlı emilen magnezyum','🧪'),
  ('Kolloidal Gümüş','Bağışıklık','5 ml','Antimikrobiyal sıvı','🧪'),
  ('Vitamin B-Complex Liquid','Vitamin','2 ml','Sıvı B kompleksi','💉')
) AS v(name, category, default_dosage, description, icon)
WHERE NOT EXISTS (
  SELECT 1 FROM public.supplements_library s WHERE s.name = v.name
);
